### ISSUE TITLE
Results page - UI

### ISSUE THREAD

**Issue by allikah1** [phax/peppol-directory#10]
Some comments in screenshots
![3b page](https://cloud.githubusercontent.com/assets/26865615/25118420/f6147e8c-241e-11e7-9295-638e8fa8ec0f.jpg)
![3a page](https://cloud.githubusercontent.com/assets/26865615/25118419/f60d5738-241e-11e7-92a9-c8b78c98b593.jpg)

**Comment by clancger** [comment]
Would it be possible to crosslink from the Document Type Titles to the actual doc type specs on either PEPPOL.eu or a local copy of the specs?
http://peppol.eu/downloads/post-award/?rel=tab404


![doc type pd listing 25 04 17](https://cloud.githubusercontent.com/assets/1429765/25409441/d5194488-2a09-11e7-8440-99bcecf140b7.jpg)

**Comment by phax** [comment]
So this is linked to #13 - requires a central document type library....

**Comment by phax** [comment]
The information are now more condensed; ordering of document types will be aligned with 13

**Comment by phax** [comment]
Closed for now - new suggestion => new issue :)
