### ISSUE TITLE
Endpoint ID format

### ISSUE THREAD

**Issue by clancger** [phax/peppol-directory#14]
I was asked last week by the PEPPOL lead in a UK hospital to point out the "actual" GLN from the string below...
iso6523-actorid-upis::0088:0827444000058

Is it possible to hide the "iso6523-actorid-upis::" prefix?

Would it make sense to link to an iso6523 list, or interpret the 0088:0827444000058 to say
GLN = 0827444000058?

https://www.galaxygw.com/iso6523/

**Comment by phax** [comment]
I can understand the reasoning but I'd like you to consider the following:
* `iso6523-actorid-upis` is part of the identifier. E.g. the Aussies use a different scheme. But for PEPPOL we may omit it, if it uses the default. Does that sound okay?
* Mapping the 4-digit prefix to an understandable name - definitively reasonable. But can only be done, if the `iso6523-actorid-upis` scheme is used - other scheme, other values :)
* The Galaxy Gateway list is nice, but unofficial. I already asked at TICC to provide a list of supported document types but got no response yet. So I will postpone the document type naming until we have a decision there.

Btw. @clancger  what do you think of the changes at #9 - does that look reasoanable to you?

**Comment by phax** [comment]
But shouldn't the full identifier be visible?? 
![issue14-1](https://cloud.githubusercontent.com/assets/196219/25398885/dc1294c2-29ed-11e7-97c3-9f3b566ba423.jpg)
What should be displayed on the second page with the details?

**Comment by clancger** [comment]
I agree the full string "iso6523-actorid-upis::9932:856922195" should be visible, somewhere. 
Possibly not necessarily in the 1st search results page, but rather in the "show detail" view?

Appreciate the variable complexity if the iso6523 prefix is not used universally

**Comment by allikah1** [comment]
But isn't 9932:856922195 the relevant info and no iso6523-actorid-upis::9932:856922195

**Comment by phax** [comment]
Both is relevant - `iso6523-actorid-upis` is the identifier scheme and `9932:856922195` is the value.
According to the PEPPOL policy, values in scheme `iso6523-actorid-upis` have the layout `agency:agencyValue`
The `agency` is e.g. 0088 for GLN or 9914 for Austrian VAT number

**Comment by clancger** [comment]
I expect there will be a mix of technical and non-technical users looking up PD, but many of whom won't understand the structure of iso6523-actorid-upis::9932:856922195, and wont be easily able to spot which part is which. 
If PD scope is expanded in future beyond current European and /or PEPPOL use cases, then oversimplifying and hiding the iso6523 prefix completely could cause a longer term issue.
Perhaps we just need to have a header above or after the string that explains the structure in words a non-technical person can understand?
eg a short human readable "identifier scheme-agency:agency value" definition

**Comment by allikah1** [comment]
can there be anything else than  iso6523-actorid-upis

**Comment by phax** [comment]
Here we have the unofficial list in PEPPOL (all in iso6523): https://www.galaxygw.com/peppol-documents/
The Aussie's use something else for their DCP/DCL stuff

**Comment by allikah1** [comment]
But those are documents and ID is for participant - I am lost in here

**Comment by allikah1** [comment]
BTW - I support Gary that interpreting ID into GLN is nice value added but full ID with 0088 should be also there

**Comment by phax** [comment]
Sorry for the confusion - too many issues discussing similar things. Mea culpa.
Here is how it looks on the live version at the moment:
![issue14-1](https://cloud.githubusercontent.com/assets/196219/25437670/6c0cea60-2a97-11e7-8926-b6a744786e78.png)

And in the details like this:

![issue14-2](https://cloud.githubusercontent.com/assets/196219/25437672/6e53462a-2a97-11e7-8ef9-c6285828d915.png)

So on the front page you only see the "simple identifier" (if being iso6523) and on the details page (second image) you see both.

**Comment by Moellre** [comment]
I think that the most important to show on the first page is the actual value. e.g. 0088:0827444000058
We cant build PD to suit providers, if we want it to be used be the suppliers.

If im putting on my "noob supplier glasses" and think of how the ERPs works, the suppliers only need the actual value.

ELMA has done this quite easy and "clean"
https://vefa.difi.no/smp/0088/0827444000058



![2017-04-28_07h55_31](https://cloud.githubusercontent.com/assets/4312390/25516035/6174cd14-2be8-11e7-963a-219731e4a726.png)

**Comment by clancger** [comment]
I agree PD should be for suppliers rather than providers, but I dont think that the ELMA View is userfriendly for anyone other than providers or the most informed participants
What I like there is the layout of the Recipient Data at the top. 
![elma recipient](https://cloud.githubusercontent.com/assets/1429765/25520627/7ce0ad0a-2bf4-11e7-81ed-80c914e81d5d.jpg)


I notice they leave out the iso6523 completely, but I think we dont have that luxury, as they plan to never have to consider accomodating other schemes

**Comment by Moellre** [comment]
I think Tickstars Participant Lookup is quite good, but there is too much info that the "end user" dont need.

![image](https://cloud.githubusercontent.com/assets/4312390/25524907/afb359ae-2c0c-11e7-8b3a-c90be262d591.png)

https://my.galaxygw.com/participantlookup
