### ISSUE TITLE
Introduction: add why only receiving capabilities are listed

### ISSUE THREAD

**Issue by phax** [phax/peppol-directory#20]
Why are sending capabilities not listed...

**Comment by clancger** [comment]
The current administrative (governance?) policy of the PEPPOL network requires that only Document Receiving capabilities of PEPPOL participants are registered on the network. There are plans to expand this in future to also encompass Document senders. 

Until then, however, PEPPOL Directory can only natively index Receivers.  Until the PEPPOL Policy changes, PEPPOL Senders without receiving capabilities would thus be invisible to PEPPOL Directory.

If a Participant has connectivity to send PEPPOL documents, (eg Invoices) but not yet receive (eg POs), then they still can be set up on PEPPOL Directory by means of a workaround, where their PEPPOL Provider creates a Dummy ID for indexing

**Comment by kirti2001** [comment]
Is this directory expanded to list senders too?

**Comment by phax** [comment]
@kirti2001  Every sender can already today register today in the Directory. It's just not technically mandatory for senders to register, but it is possible.
Just register a service group and than add the Business Card in the SMP.
