### ISSUE TITLE
Create Business Card via UI (from #22)

### ISSUE THREAD

**Issue by phax** [phax/peppol-directory#23]
Original by @clancger:
Also, it would be useful to have a "create PDBC" button, where a participant can fill out a form, that populates a simulated Business Card, and when they are happy with the contents, they can save and send on to their Access Point to be indexed

**Comment by phax** [comment]
You mean something like the stuff contained in phoss SMP:
![pd23](https://cloud.githubusercontent.com/assets/196219/26246116/b9b78600-3c97-11e7-9553-ef52d128245d.png)

**Comment by clancger** [comment]
Hi Philip, 
Way ahead of me as usual ;-)
