### ISSUE TITLE
Add Participant Name field in Service Group?

### ISSUE THREAD

**Issue by clancger** [phax/peppol-directory#29]
When creating a new service group, or viewing the list of existing service groups, can you please implement a field for the Particpant name? 
That way, in the overvieew of the service groups, it will be easier to spot an individual participant, which are only identified today by the Participant ID string

**Comment by phax** [comment]
You mean to link service group ID with Business Card name in the SMP?
As the BusinessCard feature is an optional feature would it be okay, to have this view beneath this menu item?
If so, I will move this task to the https://github.com/phax/peppol-smp-server project

**Comment by clancger** [comment]
In the SMP, the 1st step is creating a new Service Group, then to creat an associated Endpoint you select from a dropdown of Service groups, that only differ from each other using the iso6523 code. 
When the list of participants grows very long,  I can imagine that it will be more of a challenge to administer as many of the codes look alike. 
The Participant Name only gets introduced today when a PDBC is created, but if you look later in the Service Group list, there is still no cross reference to the participant name.

I think it would be useful to have a name field associated with the service group.
This could either later become part of the SDBC, or be totally unrelated and for internal use only.

From a different angle, I dont think  there is any need or benefit to show Service Group in PDBC

**Comment by phax** [comment]
I created separate issues for all items in the SMP project and therefore closing this one
