### ISSUE TITLE
Provide notifications when search results (might) exceed the 50-hit limit

### ISSUE THREAD

**Issue by johannmo** [phax/peppol-directory#33]
The current UI search returns the top 50 hits. This might confuse a user who expects a larger result set. 

A mediation could be to notify the user that there might be more participants in the result set, possibly with explanations on how to refine the search, in order to get more precise results.

**Comment by phax** [comment]
It's part of the next release

**Comment by johannmo** [comment]
Sounds good! Thanks.

Best regards Johannes Molland


Den tor. 14. jun. 2018, 12.14 skrev Philip Helger <notifications@github.com
