### ISSUE TITLE
2nd page - UI

### ISSUE THREAD

**Issue by allikah1** [phax/peppol-directory#9]
The results should be more clear:
Label in front of data
Name as the first
If more that 50 responses per search  probably start to page results with a recommendation to specify the query more
Some remarks in attachment
![2nd page](https://cloud.githubusercontent.com/assets/26865615/25118114/82432e14-241d-11e7-9868-c04db86baae4.jpg)

**Comment by phax** [comment]
I modified it locally but couldn't take all your suggestions.
I'm using a tabular style now. Please see the version for multiple hits:
![issue9-1](https://cloud.githubusercontent.com/assets/196219/25374549/21f0e8f4-299e-11e7-8f4c-e63b5d09a083.jpg)

and the version with a single hit but multiple entities:
![issue9-2](https://cloud.githubusercontent.com/assets/196219/25374572/38174ede-299e-11e7-8067-c98e367d25a4.jpg)

Does that look okay?

**Comment by clancger** [comment]
I dont see the same layout as in your screenshots above where the Country is on the line above the Entity. 
For me the Entity is still bunched against the country, and I the the screenshots aboe with separate lines is a clearer way to display.
![pd at listing 25 04 17](https://cloud.githubusercontent.com/assets/1429765/25396545/e16b9682-29dc-11e7-9d7a-a9153f8c51bb.jpg)

**Comment by phax** [comment]
This version is not yet live - I wanted to get basic feedback first :)

**Comment by clancger** [comment]
Ok, I think the (still to be published) view above looks good

**Comment by allikah1** [comment]
Musch nicer still some ocmments.
You still count that ID is more important than name though most probably in Directory most of the searches will be commited by name. I would have the name first and then ID an d all the rest
Then this scrap before the id (iso6523-actorid-upis::), could we possibly remove that?

**Comment by phax** [comment]
@allikah1 Please see #14 for how the stuff with the removed `iso6523-actorid-upis` could look like.

**Comment by phax** [comment]
@allikah1 & @clancger  New version is online

**Comment by Moellre** [comment]
@allikah1 has a very good point regarding the name.

I think that the value shuould be at the top, but then the Name should be second.

**Comment by clancger** [comment]
Ok, I think we're now getting close to where we need to be..
I wolud insert the PEPPOL ENDPOINT, or perhaps just Endpoint in the csae we oneday have non-PEPPOL IDs here. Thats at the top of Business Information and Document Types pages

Full **PEPPOL ENDPOINT** ID: iso6523-actorid-upis::9932:856922195

**Comment by clancger** [comment]
Also, on the Document Types page, other than the search term still being visible in the search window at the very top, the Participant name is not shown, so I'd pull that in too, just for clarity

**Comment by phax** [comment]
1. @clancger The text is now: `Full PEPPOL participant ID: iso6523-actorid-upis::9915:test`
2. @clancger The name of the entity on top of the document types: this is tricky if many entities are available for a single participant. How shall the names be represented? Or shall we not use tabs at all, and show the document types below???

**Comment by clancger** [comment]
1) that's fine
2) I'd say just the top level name thats shown on the  "Business Information" page. 
I think it's cleaner in the tabbed format as we have it now

**Comment by phax** [comment]
Ad 2. You mean that if a participant has multiple entities, only the first one is shown (maybe with some "..." afterwards)?

**Comment by clancger** [comment]
If a participant has multiple entries inside a single Business Card, I'd still be showing no more than the business Card entity name. The reason for showing then headline name on the Capabilities page is just so that a viewer doesnt get confused

**Comment by phax** [comment]
This is how it looks now with 3 entities in a single Business Card:
![issue9-3](https://cloud.githubusercontent.com/assets/196219/25616579/fbbe8362-2f3d-11e7-84eb-e58887a809b2.png)
![issue9-4](https://cloud.githubusercontent.com/assets/196219/25616578/fb88062a-2f3d-11e7-9ee4-7daca0655990.png)
Any changes?
Otherwise I put it on the server like this.

**Comment by clancger** [comment]
I like it

**Comment by phax** [comment]
It will be on the server like this in the next hour.
If you need more, please open a new issue - thx.

**Comment by allikah1** [comment]
HI

Can you once again review the look and feel of search results and Details. Search results is nice but I owuld try t omake details page look like a bit same: Font size, table with…

Ahti

**Comment by phax** [comment]
Okay Ahti - lets work on the details by Skype, and I will create a new issue with the tasks
